x-custom-image: &custom_image
  image: castlecraft/erpnext-webshop:version-15
  pull_policy: always
  deploy:
    restart_policy:
      condition: always

services:
  backend:
    <<: *custom_image
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - bench-network
# ... el resto del archivo sigue igual ...
